// Offline technology signature database.
//
// Each technology lists one or more rules. Any matching rule marks it as detected; a capture
// group (or a version-like global value) supplies the version.
//
//   probe   dotted global paths read in the page's MAIN world, e.g. 'jQuery.fn.jquery'.
//           An inner array means "all of these must exist" (version comes from the first).
//   special key of a structural probe computed in the page (see lib/probe.js, content/collector.js).
//   url     regexes tested against script, stylesheet and network request URLs.
//   meta    { metaName: regex } tested against <meta name|property|http-equiv> contents.
//   dom     CSS selectors; any match counts.
//   headers { headerName: regex } tested against the main document's response headers.
//   cookies cookie names (string = exact, RegExp = pattern), from document.cookie and Set-Cookie.
//   cssVar  custom properties defined on :root/body.
//   host    regexes tested against the page hostname.
//   notHost regexes; the technology is never reported on matching hostnames.
//   comment regexes tested against HTML comments.
//   ids     key into collected tag IDs (ga4, ua, gtm, aw).
//   implies other technology names that must also be present.
//   tracker privacy classification: analytics | advertising | replay | social | marketing | fingerprinting
//   friendly true for privacy-focused analytics (not counted as trackers).

export const CATEGORIES = [
  ['cms', 'CMS'],
  ['ecommerce', 'E-commerce'],
  ['webframework', 'Web frameworks & site generators'],
  ['framework', 'JavaScript frameworks'],
  ['backend', 'Backend & languages'],
  ['server', 'Web servers'],
  ['hosting', 'Hosting & PaaS'],
  ['cdn', 'CDN & edge'],
  ['ui', 'UI & CSS frameworks'],
  ['fonts', 'Fonts & icons'],
  ['library', 'JavaScript libraries'],
  ['analytics', 'Analytics'],
  ['tagmanager', 'Tag managers'],
  ['advertising', 'Advertising'],
  ['marketing', 'Marketing automation'],
  ['abtesting', 'A/B testing & feature flags'],
  ['consent', 'Cookie consent'],
  ['monitoring', 'Monitoring & RUM'],
  ['support', 'Live chat & support'],
  ['payments', 'Payments'],
  ['security', 'Security & bot protection'],
  ['auth', 'Auth & backend services'],
  ['media', 'Video & media'],
  ['widgets', 'Widgets & embeds'],
  ['wordpress', 'WordPress plugins & themes'],
  ['platform', 'Platform & protocols'],
];

const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/** URL on `domain` (or any subdomain), optionally followed by a path regex fragment. */
const d = (domain, path = '') => new RegExp(`^https?://(?:[^/?#]*\\.)?${esc(domain)}(?::\\d+)?/${path}`, 'i');

/** npm-style CDN URLs (jsDelivr, unpkg, cdnjs) with a version capture. */
const cdn = (pkg, cdnjsName = pkg) => [
  new RegExp(`(?:/npm/|unpkg\\.com/|esm\\.sh/|skypack\\.dev/)${esc(pkg)}@v?(\\d+\\.\\d+(?:\\.\\d+)?)`, 'i'),
  new RegExp(`/ajax/libs/${esc(cdnjsName)}/(\\d+\\.\\d+(?:\\.\\d+)?)/`, 'i'),
];

const GEN = (re) => ({ generator: re });

export const TECHNOLOGIES = [
  // ---------------------------------------------------------------- CMS
  { name: 'WordPress', cat: 'cms', meta: GEN(/^WordPress ?([\d.]+)?/i), url: [/\/wp-(?:content|includes)\//i], dom: ['link[rel="https://api.w.org/"]'], cssVar: ['--wp--preset--color--black', '--wp--style--global--content-size'], headers: { link: /rel="https:\/\/api\.w\.org\/"/i, 'x-pingback': /xmlrpc\.php/i }, implies: ['PHP'] },
  { name: 'Drupal', cat: 'cms', meta: GEN(/^Drupal ?(\d+)?/i), headers: { 'x-generator': /Drupal ?(\d+)?/i, 'x-drupal-cache': /./, 'x-drupal-dynamic-cache': /./ }, probe: ['drupalSettings', 'Drupal.behaviors'], url: [/\/sites\/(?:default|all)\/(?:files|modules|themes)\//i, /\/core\/misc\/drupal(?:\.init)?\.js/i], implies: ['PHP'] },
  { name: 'Joomla', cat: 'cms', meta: GEN(/Joomla!? ?([\d.]+)?/i), probe: ['Joomla.getOptions'], url: [/\/media\/(?:jui|system)\/js\//i], implies: ['PHP'] },
  { name: 'Ghost', cat: 'cms', meta: GEN(/^Ghost ?([\d.]+)?/i), headers: { 'x-ghost-cache-status': /./ }, url: [/\/ghost\/(?:portal|sodo-search)@/i] },
  { name: 'Squarespace', cat: 'cms', probe: ['Static.SQUARESPACE_CONTEXT', 'Squarespace'], url: [d('squarespace.com'), d('squarespace-cdn.com'), d('sqspcdn.com')], headers: { server: /Squarespace/i } },
  { name: 'Wix', cat: 'cms', meta: GEN(/Wix\.com Website Builder/i), headers: { 'x-wix-request-id': /./, server: /Pepyaka/i }, url: [d('parastorage.com'), d('wixstatic.com')], host: [/\.wixsite\.com$/] },
  { name: 'Webflow', cat: 'cms', meta: GEN(/^Webflow/i), dom: ['html[data-wf-site]', 'html[data-wf-page]'], url: [d('website-files.com'), d('webflow.com', 'css/')], host: [/\.webflow\.io$/] },
  { name: 'Framer', cat: 'cms', meta: GEN(/^Framer ?([\w.]+)?/i), url: [d('framerusercontent.com'), d('framer.com', 'm/')], host: [/\.framer\.(?:app|website)$/] },
  { name: 'HubSpot CMS', cat: 'cms', meta: GEN(/^HubSpot/i), headers: { 'x-hs-hub-id': /./ } },
  { name: 'Contentful', cat: 'cms', url: [d('ctfassets.net')] },
  { name: 'Sanity', cat: 'cms', url: [d('cdn.sanity.io')] },
  { name: 'Storyblok', cat: 'cms', url: [d('storyblok.com')] },
  { name: 'Prismic', cat: 'cms', url: [d('prismic.io')] },
  { name: 'Strapi', cat: 'cms', headers: { 'x-powered-by': /Strapi/i } },
  { name: 'TYPO3', cat: 'cms', meta: GEN(/TYPO3 ?([\d.]+)?/i), url: [/\/typo3(?:conf|temp)\//i], implies: ['PHP'] },
  { name: 'Craft CMS', cat: 'cms', headers: { 'x-powered-by': /Craft CMS/i }, cookies: ['CraftSessionId'], implies: ['PHP'] },
  { name: 'Sitecore', cat: 'cms', cookies: ['SC_ANALYTICS_GLOBAL_COOKIE', 'sxa_site'], url: [/\/-\/media\/[^?]+\.(?:ashx|jpg|png|svg)/i] },
  { name: 'Adobe Experience Manager', cat: 'cms', url: [/\/etc\.clientlibs\//i, /\/etc\/designs\//i] },
  { name: 'Blogger', cat: 'cms', meta: GEN(/^Blogger$/i), host: [/\.blogspot\.com$/] },
  { name: 'Medium', cat: 'cms', url: [d('cdn-client.medium.com')] },
  { name: 'Substack', cat: 'cms', url: [d('substackcdn.com')], host: [/\.substack\.com$/] },
  { name: 'Tumblr', cat: 'cms', url: [d('assets.tumblr.com')], host: [/\.tumblr\.com$/] },
  { name: 'MediaWiki', cat: 'cms', meta: GEN(/^MediaWiki ?([\d.]+)?/i), probe: ['mw.config'], implies: ['PHP'] },
  { name: 'Discourse', cat: 'cms', meta: GEN(/^Discourse ?([\d.]+)?/i), implies: ['Ruby on Rails', 'Ember.js'] },
  { name: 'Tilda', cat: 'cms', url: [d('tildacdn.com')] },
  { name: 'Weebly', cat: 'cms', url: [d('editmysite.com')] },
  { name: 'Duda', cat: 'cms', url: [d('multiscreensite.com'), d('dudamobile.com')] },
  { name: 'GitBook', cat: 'cms', meta: GEN(/^GitBook/i) },
  { name: 'Notion', cat: 'cms', host: [/\.notion\.site$/] },

  // ---------------------------------------------------------------- E-commerce
  { name: 'Shopify', cat: 'ecommerce', probe: ['Shopify.shop', 'Shopify.theme'], url: [d('cdn.shopify.com'), d('shopifycdn.net')], headers: { 'x-shopid': /./, 'x-shopify-stage': /./, 'powered-by': /Shopify/i }, cookies: ['_shopify_y', '_shopify_s'], host: [/\.myshopify\.com$/] },
  { name: 'WooCommerce', cat: 'ecommerce', meta: GEN(/^WooCommerce ?([\d.]+)?/i), url: [/\/plugins\/woocommerce\//i], dom: ['body.woocommerce', 'body.woocommerce-page', '.woocommerce'], cookies: ['woocommerce_cart_hash', 'woocommerce_items_in_cart'], implies: ['WordPress'] },
  { name: 'Magento', cat: 'ecommerce', url: [/\/static\/(?:version\d+\/)?frontend\/[^/]+\/[^/]+\/[a-z]{2}_[A-Z]{2}\//, /\/skin\/frontend\//i], dom: ['script[type="text/x-magento-init"]'], cookies: ['X-Magento-Vary'], implies: ['PHP'] },
  { name: 'BigCommerce', cat: 'ecommerce', probe: ['BCData'], url: [d('bigcommerce.com')] },
  { name: 'PrestaShop', cat: 'ecommerce', meta: GEN(/PrestaShop/i), probe: ['prestashop.urls'], cookies: [/^PrestaShop-/], implies: ['PHP'] },
  { name: 'OpenCart', cat: 'ecommerce', cookies: ['OCSESSID'], url: [/catalog\/view\/javascript\//i], implies: ['PHP'] },
  { name: 'Ecwid', cat: 'ecommerce', probe: ['Ecwid.getOwnerId'], url: [d('ecwid.com')] },
  { name: 'Salesforce Commerce Cloud', cat: 'ecommerce', url: [/\/on\/demandware\.static\//i], cookies: ['dwsid', /^dwanonymous_/] },
  { name: 'Snipcart', cat: 'ecommerce', url: [d('snipcart.com')] },

  // ---------------------------------------------------------------- Web frameworks & SSG
  { name: 'Next.js', cat: 'webframework', probe: ['next.version', '__NEXT_DATA__.buildId', '__next_f'], dom: ['#__next', 'script#__NEXT_DATA__'], url: [/\/_next\/static\//], headers: { 'x-powered-by': /Next\.js ?([\d.]+)?/i, 'x-nextjs-cache': /./, 'x-nextjs-prerender': /./ }, implies: ['React'] },
  { name: 'Nuxt', cat: 'webframework', probe: ['__NUXT__', '$nuxt', 'useNuxtApp'], dom: ['#__nuxt', 'script#__NUXT_DATA__'], url: [/\/_nuxt\//], headers: { 'x-powered-by': /Nuxt/i }, implies: ['Vue.js'] },
  { name: 'Gatsby', cat: 'webframework', meta: GEN(/^Gatsby ?([\d.]+)?/i), dom: ['#___gatsby'], probe: ['___loader'], implies: ['React'] },
  { name: 'Remix', cat: 'webframework', probe: ['__remixContext'], implies: ['React'] },
  { name: 'React Router', cat: 'webframework', probe: ['__reactRouterVersion', '__reactRouterContext'], implies: ['React'] },
  { name: 'Astro', cat: 'webframework', meta: GEN(/^Astro v?([\d.]+)?/i), dom: ['astro-island', 'astro-slot'], url: [/\/_astro\//] },
  { name: 'SvelteKit', cat: 'webframework', dom: ['[data-sveltekit-preload-data]', '[data-sveltekit-hydrate]'], url: [/\/_app\/immutable\//], implies: ['Svelte'] },
  { name: 'Docusaurus', cat: 'webframework', meta: GEN(/^Docusaurus ?v?([\d.]+)?/i), implies: ['React'] },
  { name: 'VitePress', cat: 'webframework', meta: GEN(/^VitePress ?v?([\d.]+)?/i), implies: ['Vue.js'] },
  { name: 'VuePress', cat: 'webframework', meta: GEN(/^VuePress ?([\d.]+)?/i), implies: ['Vue.js'] },
  { name: 'Hugo', cat: 'webframework', meta: GEN(/^Hugo ?([\d.]+)?/i) },
  { name: 'Jekyll', cat: 'webframework', meta: GEN(/^Jekyll ?v?([\d.]+)?/i) },
  { name: 'Eleventy', cat: 'webframework', meta: GEN(/^Eleventy ?v?([\d.]+)?/i) },
  { name: 'Hexo', cat: 'webframework', meta: GEN(/^Hexo ?([\d.]+)?/i) },
  { name: 'MkDocs', cat: 'webframework', meta: GEN(/^mkdocs-([\d.]+)/i) },
  { name: 'Sphinx', cat: 'webframework', probe: ['DOCUMENTATION_OPTIONS'], url: [/_static\/(?:doctools|sphinx_highlight)\.js/i] },
  { name: 'Vite dev server', cat: 'webframework', url: [/\/@vite\/client(?:[?#]|$)/] },
  { name: 'Blazor', cat: 'webframework', probe: ['Blazor'], url: [/_framework\/blazor\.(?:web|server|webassembly)\.js/i], implies: ['ASP.NET'] },

  // ---------------------------------------------------------------- JavaScript frameworks
  { name: 'React', cat: 'framework', probe: ['React.version'], special: 'react', dom: ['[data-reactroot]', '[data-reactid]'], url: [...cdn('react'), ...cdn('react-dom'), /\/react(?:-dom)?(?:\.production)?(?:\.min)?\.js(?:[?#]|$)/i] },
  { name: 'Vue.js', cat: 'framework', probe: ['Vue.version'], special: 'vue', dom: ['[data-v-app]', '[data-server-rendered]'], url: [...cdn('vue'), /\/vue(?:\.runtime)?(?:\.global)?(?:\.prod)?(?:\.min)?\.js(?:[?#]|$)/i] },
  { name: 'Angular', cat: 'framework', special: 'angular', dom: ['[ng-version]'] },
  { name: 'AngularJS', cat: 'framework', probe: ['angular.version.full'], dom: ['[ng-app]', '[data-ng-app]', '.ng-scope', '[ng-controller]'], url: [...cdn('angular', 'angular.js'), /\/angular(?:\.min)?\.js(?:[?#]|$)/i] },
  { name: 'Svelte', cat: 'framework', special: 'svelte', dom: ['[class*="svelte-"]'] },
  { name: 'SolidJS', cat: 'framework', probe: ['_$HY'] },
  { name: 'Preact', cat: 'framework', probe: [['preact.h', 'preact.render']], url: [...cdn('preact'), /\/preact(?:\.min)?\.js(?:[?#]|$)/i] },
  { name: 'Qwik', cat: 'framework', dom: ['[q\\:container]', 'script[type="qwik/json"]'] },
  { name: 'Lit', cat: 'framework', probe: ['litElementVersions.0', 'litHtmlVersions.0'] },
  { name: 'Ember.js', cat: 'framework', probe: ['Ember.VERSION'], dom: ['.ember-application', '.ember-view'] },
  { name: 'Backbone.js', cat: 'framework', probe: ['Backbone.VERSION'] },
  { name: 'Alpine.js', cat: 'framework', probe: ['Alpine.version'], dom: ['[x-data]'] },
  { name: 'htmx', cat: 'framework', probe: ['htmx.version'], dom: ['[hx-get]', '[hx-post]', '[data-hx-get]', '[data-hx-post]', '[hx-boost]'] },
  { name: 'Stimulus', cat: 'framework', probe: ['Stimulus.router'] },
  { name: 'Turbo', cat: 'framework', probe: ['Turbo.session'], dom: ['turbo-frame'] },
  { name: 'Turbolinks', cat: 'framework', probe: ['Turbolinks.supported'] },
  { name: 'Knockout.js', cat: 'framework', probe: ['ko.version'] },
  { name: 'Livewire', cat: 'framework', probe: ['Livewire'], dom: ['[wire\\:id]', '[wire\\:snapshot]'], implies: ['Laravel'] },
  { name: 'Inertia.js', cat: 'framework', dom: ['#app[data-page]'] },
  { name: 'Unpoly', cat: 'framework', probe: ['up.version'] },
  { name: 'Phoenix LiveView', cat: 'framework', dom: ['[data-phx-main]', '[data-phx-session]'], implies: ['Elixir'] },

  // ---------------------------------------------------------------- Backend & languages
  { name: 'PHP', cat: 'backend', headers: { 'x-powered-by': /PHP\/?([\d.]+)?/i }, cookies: ['PHPSESSID'] },
  { name: 'ASP.NET', cat: 'backend', headers: { 'x-aspnet-version': /([\d.]+)/, 'x-powered-by': /ASP\.NET/i, 'x-aspnetmvc-version': /./ }, cookies: ['ASP.NET_SessionId', /^\.AspNetCore\./], dom: ['input[name="__VIEWSTATE"]', 'input[name="__RequestVerificationToken"]'] },
  { name: 'Express', cat: 'backend', headers: { 'x-powered-by': /^Express$/i }, implies: ['Node.js'] },
  { name: 'Node.js', cat: 'backend', cookies: ['connect.sid'] },
  { name: 'Django', cat: 'backend', cookies: ['csrftoken', 'django_language'], dom: ['input[name="csrfmiddlewaretoken"]'], implies: ['Python'] },
  { name: 'Flask', cat: 'backend', headers: { server: /Werkzeug\/?([\d.]+)?/i }, implies: ['Python'] },
  { name: 'Python', cat: 'backend', headers: { server: /\bPython\/?([\d.]+)?/i } },
  { name: 'Laravel', cat: 'backend', cookies: ['laravel_session'], implies: ['PHP'] },
  { name: 'Symfony', cat: 'backend', headers: { 'x-debug-token': /./ }, cookies: ['sf_redirect'], implies: ['PHP'] },
  { name: 'CodeIgniter', cat: 'backend', cookies: ['ci_session'], implies: ['PHP'] },
  { name: 'CakePHP', cat: 'backend', cookies: ['CAKEPHP'], implies: ['PHP'] },
  { name: 'Ruby on Rails', cat: 'backend', meta: { 'csrf-param': /^authenticity_token$/ }, headers: { 'x-runtime': /^[\d.]+$/ }, implies: ['Ruby'] },
  { name: 'Ruby', cat: 'backend', headers: { server: /Phusion Passenger|Puma|Unicorn/i } },
  { name: 'Java', cat: 'backend', cookies: ['JSESSIONID'], headers: { 'x-powered-by': /Servlet|JSP/i } },
  { name: 'Elixir', cat: 'backend' },

  // ---------------------------------------------------------------- Web servers
  { name: 'Nginx', cat: 'server', headers: { server: /nginx(?:\/([\d.]+))?/i } },
  { name: 'OpenResty', cat: 'server', headers: { server: /openresty(?:\/([\d.]+))?/i }, implies: ['Nginx'] },
  { name: 'Apache HTTP Server', cat: 'server', headers: { server: /^Apache(?!-Coyote)(?:\/([\d.]+))?/i } },
  { name: 'Apache Tomcat', cat: 'server', headers: { server: /Apache-Coyote|Tomcat/i }, implies: ['Java'] },
  { name: 'Microsoft IIS', cat: 'server', headers: { server: /Microsoft-IIS(?:\/([\d.]+))?/i } },
  { name: 'LiteSpeed', cat: 'server', headers: { server: /LiteSpeed/i, 'x-litespeed-cache': /./ } },
  { name: 'Caddy', cat: 'server', headers: { server: /^Caddy/i } },
  { name: 'Envoy', cat: 'server', headers: { server: /^envoy/i, 'x-envoy-upstream-service-time': /./ } },
  { name: 'Kestrel', cat: 'server', headers: { server: /Kestrel/i }, implies: ['ASP.NET'] },
  { name: 'Jetty', cat: 'server', headers: { server: /Jetty(?:\(([\d.]+))?/i }, implies: ['Java'] },
  { name: 'Gunicorn', cat: 'server', headers: { server: /gunicorn(?:\/([\d.]+))?/i }, implies: ['Python'] },
  { name: 'Uvicorn', cat: 'server', headers: { server: /uvicorn/i }, implies: ['Python'] },
  { name: 'Cowboy', cat: 'server', headers: { server: /^Cowboy/i } },
  { name: 'Varnish', cat: 'server', headers: { 'x-varnish': /./, via: /varnish/i } },
  { name: 'Google Web Server', cat: 'server', headers: { server: /^gws$/i } },

  // ---------------------------------------------------------------- Hosting
  { name: 'Vercel', cat: 'hosting', headers: { server: /^Vercel$/i, 'x-vercel-id': /./, 'x-vercel-cache': /./ }, host: [/\.vercel\.app$/] },
  { name: 'Netlify', cat: 'hosting', headers: { server: /^Netlify$/i, 'x-nf-request-id': /./ }, host: [/\.netlify\.app$/] },
  { name: 'GitHub Pages', cat: 'hosting', headers: { server: /^GitHub\.com$/ }, host: [/\.github\.io$/], notHost: [/(?:^|\.)github\.com$/] },
  { name: 'GitLab Pages', cat: 'hosting', host: [/\.gitlab\.io$/] },
  { name: 'Cloudflare Pages', cat: 'hosting', host: [/\.pages\.dev$/] },
  { name: 'Cloudflare Workers', cat: 'hosting', host: [/\.workers\.dev$/] },
  { name: 'Firebase Hosting', cat: 'hosting', host: [/\.(?:web\.app|firebaseapp\.com)$/], url: [/\/__\/firebase\//] },
  { name: 'Heroku', cat: 'hosting', headers: { via: /vegur/i }, host: [/\.herokuapp\.com$/] },
  { name: 'Render', cat: 'hosting', headers: { 'x-render-origin-server': /./, 'rndr-id': /./ }, host: [/\.onrender\.com$/] },
  { name: 'Fly.io', cat: 'hosting', headers: { 'fly-request-id': /./, server: /^Fly\//i }, host: [/\.fly\.dev$/] },
  { name: 'Railway', cat: 'hosting', host: [/\.up\.railway\.app$/] },
  { name: 'Amazon S3', cat: 'hosting', headers: { server: /^AmazonS3$/i } },
  { name: 'AWS Elastic Load Balancing', cat: 'hosting', headers: { server: /^awselb/i }, cookies: ['AWSALB', 'AWSALBCORS', 'AWSELB'] },
  { name: 'AWS Amplify', cat: 'hosting', host: [/\.amplifyapp\.com$/] },
  { name: 'Azure App Service', cat: 'hosting', cookies: ['ARRAffinity', 'ARRAffinitySameSite'], host: [/\.azurewebsites\.net$/, /\.azurestaticapps\.net$/] },
  { name: 'Google Cloud', cat: 'hosting', headers: { server: /^Google Frontend$/i, via: /1\.1 google/i, 'x-cloud-trace-context': /./ }, host: [/\.appspot\.com$/, /\.run\.app$/] },
  { name: 'WP Engine', cat: 'hosting', headers: { 'x-powered-by': /WP Engine/i, 'wpe-backend': /./ }, implies: ['WordPress'] },
  { name: 'Kinsta', cat: 'hosting', headers: { 'x-kinsta-cache': /./ }, implies: ['WordPress'] },
  { name: 'Pantheon', cat: 'hosting', headers: { 'x-pantheon-styx-hostname': /./ } },
  { name: 'Acquia', cat: 'hosting', headers: { 'x-ah-environment': /./ } },
  { name: 'Hostinger', cat: 'hosting', headers: { platform: /hostinger/i, panel: /hpanel/i } },
  { name: 'WordPress.com', cat: 'hosting', host: [/\.wordpress\.com$/], headers: { 'host-header': /WordPress\.com/i }, implies: ['WordPress'] },
  { name: 'Deno Deploy', cat: 'hosting', host: [/\.deno\.dev$/] },

  // ---------------------------------------------------------------- CDN & edge
  { name: 'Cloudflare', cat: 'cdn', headers: { server: /^cloudflare$/i, 'cf-ray': /./, 'cf-cache-status': /./ }, cookies: ['__cf_bm', 'cf_clearance', '__cflb'], url: [/\/cdn-cgi\/(?:challenge-platform|scripts|rum|zaraz)\//] },
  { name: 'Amazon CloudFront', cat: 'cdn', headers: { 'x-amz-cf-id': /./, 'x-amz-cf-pop': /./, via: /CloudFront/i, 'x-cache': /cloudfront/i } },
  { name: 'Fastly', cat: 'cdn', headers: { 'x-fastly-request-id': /./, 'fastly-debug-digest': /./, 'x-served-by': /^cache-/i } },
  { name: 'Akamai', cat: 'cdn', headers: { 'x-akamai-transformed': /./, 'akamai-grn': /./, 'x-akamai-request-id': /./, server: /AkamaiGHost|AkamaiNetStorage/i } },
  { name: 'Azure Front Door', cat: 'cdn', headers: { 'x-azure-ref': /./ } },
  { name: 'BunnyCDN', cat: 'cdn', headers: { server: /^BunnyCDN/i }, url: [d('b-cdn.net')] },
  { name: 'KeyCDN', cat: 'cdn', headers: { server: /^keycdn/i } },
  { name: 'CDN77', cat: 'cdn', headers: { server: /^CDN77/i } },
  { name: 'jsDelivr', cat: 'cdn', url: [d('cdn.jsdelivr.net')] },
  { name: 'cdnjs', cat: 'cdn', url: [d('cdnjs.cloudflare.com')] },
  { name: 'unpkg', cat: 'cdn', url: [d('unpkg.com')] },
  { name: 'Google Hosted Libraries', cat: 'cdn', url: [d('ajax.googleapis.com')] },
  { name: 'Cloudinary', cat: 'cdn', url: [d('res.cloudinary.com')] },
  { name: 'imgix', cat: 'cdn', url: [d('imgix.net')] },
  { name: 'ImageKit', cat: 'cdn', url: [d('ik.imagekit.io')] },

  // ---------------------------------------------------------------- UI & CSS
  { name: 'Bootstrap', cat: 'ui', probe: ['bootstrap.Tooltip.VERSION', 'jQuery.fn.tooltip.Constructor.VERSION'], url: [...cdn('bootstrap', 'twitter-bootstrap'), /\/bootstrap(?:\.bundle)?(?:\.min)?\.(?:css|js)(?:[?#]|$)/i], cssVar: ['--bs-blue', '--bs-body-bg'] },
  { name: 'Tailwind CSS', cat: 'ui', special: 'tailwind', cssVar: ['--tw-ring-offset-width', '--tw-ring-color'], url: [...cdn('tailwindcss'), d('cdn.tailwindcss.com')] },
  { name: 'Material UI', cat: 'ui', dom: ['[class*="MuiButton-root"]', '[class*="MuiTypography-root"]', '[class*="MuiBox-root"]', '[class*="MuiPaper-root"]'], implies: ['React'] },
  { name: 'Chakra UI', cat: 'ui', dom: ['[class*="chakra-"]'], cssVar: ['--chakra-ring-offset-width', '--chakra-colors-gray-100'], implies: ['React'] },
  { name: 'Ant Design', cat: 'ui', dom: ['.ant-btn', '.ant-layout', '.ant-row'] },
  { name: 'Mantine', cat: 'ui', dom: ['[class*="mantine-"]'], cssVar: ['--mantine-color-body'], implies: ['React'] },
  { name: 'Vuetify', cat: 'ui', dom: ['.v-application'], implies: ['Vue.js'] },
  { name: 'Quasar', cat: 'ui', probe: ['Quasar.version'], implies: ['Vue.js'] },
  { name: 'Element Plus', cat: 'ui', dom: ['.el-button', '.el-input__inner', '.el-row'], implies: ['Vue.js'] },
  { name: 'Bulma', cat: 'ui', url: [...cdn('bulma'), /\/bulma(?:\.min)?\.css/i], cssVar: ['--bulma-primary-h'] },
  { name: 'Foundation', cat: 'ui', probe: ['Foundation.version'], url: [/\/foundation(?:\.min)?\.css/i] },
  { name: 'UIkit', cat: 'ui', probe: ['UIkit.version'], dom: ['[uk-grid]', '[uk-navbar]'] },
  { name: 'Semantic UI', cat: 'ui', url: [/\/semantic(?:\.min)?\.css/i] },
  { name: 'Materialize', cat: 'ui', url: [/\/materialize(?:\.min)?\.css/i] },
  { name: 'daisyUI', cat: 'ui', cssVar: ['--rounded-box', '--rounded-btn'] },
  { name: 'Radix UI', cat: 'ui', dom: ['[data-radix-popper-content-wrapper]', '[data-radix-scroll-area-viewport]', '[data-radix-collection-item]'], implies: ['React'] },
  { name: 'Headless UI', cat: 'ui', dom: ['[id^="headlessui-"]'] },
  { name: 'Animate.css', cat: 'ui', dom: ['.animate__animated'], url: [/\/animate(?:\.min)?\.css/i] },
  { name: 'styled-components', cat: 'ui', dom: ['style[data-styled]', 'style[data-styled-version]'] },
  { name: 'Emotion', cat: 'ui', dom: ['style[data-emotion]'] },

  // ---------------------------------------------------------------- Fonts & icons
  { name: 'Google Fonts', cat: 'fonts', url: [d('fonts.googleapis.com'), d('fonts.gstatic.com')] },
  { name: 'Adobe Fonts', cat: 'fonts', url: [d('use.typekit.net'), d('p.typekit.net')] },
  { name: 'Bunny Fonts', cat: 'fonts', url: [d('fonts.bunny.net')] },
  { name: 'Font Awesome', cat: 'fonts', probe: ['FontAwesome'], url: [/font-?awesome/i, d('kit.fontawesome.com'), d('ka-f.fontawesome.com')], dom: ['.fa-solid', '.fas', '.fab', '.fa-brands'] },
  { name: 'Material Icons', cat: 'fonts', url: [/fonts\.googleapis\.com\/(?:icon|css2?)\?family=Material\+(?:Icons|Symbols)/i], dom: ['.material-icons', '.material-symbols-outlined', '.material-symbols-rounded'] },
  { name: 'Bootstrap Icons', cat: 'fonts', url: [/bootstrap-icons/i], dom: ['i.bi[class*="bi-"]'] },
  { name: 'Ionicons', cat: 'fonts', dom: ['ion-icon'], url: [/ionicons/i] },

  // ---------------------------------------------------------------- JavaScript libraries
  { name: 'jQuery', cat: 'library', probe: ['jQuery.fn.jquery', '$.fn.jquery'], url: [...cdn('jquery'), /\/jquery\/(\d+\.\d+\.\d+)\/jquery/i, /jquery-(\d+\.\d+\.\d+)(?:\.slim)?(?:\.min)?\.js/i, /\/jquery(?:\.slim)?(?:\.min)?\.js\?ver=(\d+\.\d+\.\d+)/i, /\/jquery(?:\.slim)?(?:\.min)?\.js(?:[?#]|$)/i] },
  { name: 'jQuery UI', cat: 'library', probe: ['jQuery.ui.version'], url: [...cdn('jquery-ui', 'jqueryui'), /jquery-ui(?:\.min)?\.js/i], implies: ['jQuery'] },
  { name: 'jQuery Migrate', cat: 'library', probe: ['jQuery.migrateVersion'], url: [/jquery-migrate(?:-(\d+\.\d+\.\d+))?(?:\.min)?\.js/i], implies: ['jQuery'] },
  { name: 'Lodash', cat: 'library', probe: [['_.VERSION', '_.flattenDeep'], 'lodash.VERSION'], url: [...cdn('lodash', 'lodash.js'), /\/lodash(?:\.min)?\.js(?:[?#]|$)/i] },
  { name: 'Underscore.js', cat: 'library', probe: [['_.VERSION', '_.findWhere']], url: [...cdn('underscore', 'underscore.js'), /\/underscore(?:-min|\.min)?\.js(?:[?#]|$)/i] },
  { name: 'Moment.js', cat: 'library', probe: ['moment.version'], url: [...cdn('moment', 'moment.js'), /\/moment(?:-with-locales)?(?:\.min)?\.js(?:[?#]|$)/i] },
  { name: 'Day.js', cat: 'library', probe: [['dayjs.extend', 'dayjs.locale']], url: [...cdn('dayjs')] },
  { name: 'Luxon', cat: 'library', probe: ['luxon.VERSION', 'luxon.DateTime'] },
  { name: 'Axios', cat: 'library', probe: ['axios.VERSION', 'axios.interceptors'], url: [...cdn('axios'), /\/axios(?:\.min)?\.js(?:[?#]|$)/i] },
  { name: 'GSAP', cat: 'library', probe: ['gsap.version', 'TweenMax.version'], url: [...cdn('gsap')] },
  { name: 'Three.js', cat: 'library', probe: ['THREE.REVISION'], url: [...cdn('three', 'three.js')] },
  { name: 'D3', cat: 'library', probe: ['d3.version'], url: [...cdn('d3'), /\/d3(?:\.v\d)?(?:\.min)?\.js(?:[?#]|$)/i] },
  { name: 'Chart.js', cat: 'library', probe: ['Chart.version'], url: [...cdn('chart.js', 'Chart.js')] },
  { name: 'Highcharts', cat: 'library', probe: ['Highcharts.version'], url: [d('code.highcharts.com')] },
  { name: 'ECharts', cat: 'library', probe: ['echarts.version'], url: [...cdn('echarts')] },
  { name: 'ApexCharts', cat: 'library', probe: ['ApexCharts.exec'], url: [...cdn('apexcharts')] },
  { name: 'Plotly', cat: 'library', probe: ['Plotly.version'] },
  { name: 'Leaflet', cat: 'library', probe: [['L.version', 'L.map', 'L.tileLayer']], url: [...cdn('leaflet'), /\/leaflet(?:-src)?(?:\.min)?\.(?:js|css)(?:[?#]|$)/i] },
  { name: 'Mapbox GL JS', cat: 'library', probe: ['mapboxgl.version'], url: [d('api.mapbox.com', 'mapbox-gl-js/v(\\d+\\.\\d+\\.\\d+)')] },
  { name: 'MapLibre GL', cat: 'library', url: [...cdn('maplibre-gl')] },
  { name: 'Swiper', cat: 'library', probe: ['Swiper'], dom: ['.swiper-wrapper', 'swiper-container'], url: [...cdn('swiper')] },
  { name: 'Slick', cat: 'library', probe: ['jQuery.fn.slick'], dom: ['.slick-slider'], implies: ['jQuery'] },
  { name: 'Owl Carousel', cat: 'library', probe: ['jQuery.fn.owlCarousel'], dom: ['.owl-carousel'], implies: ['jQuery'] },
  { name: 'Splide', cat: 'library', probe: ['Splide'], dom: ['.splide__track'] },
  { name: 'Flickity', cat: 'library', probe: ['Flickity'], dom: ['.flickity-enabled'] },
  { name: 'Lottie', cat: 'library', probe: ['lottie.version', 'bodymovin.version'], dom: ['lottie-player', 'dotlottie-player', 'dotlottie-wc'] },
  { name: 'AOS', cat: 'library', probe: ['AOS.init'], dom: ['[data-aos]'] },
  { name: 'Lenis', cat: 'library', probe: ['lenisVersion'], dom: ['html.lenis'] },
  { name: 'Barba.js', cat: 'library', probe: ['barba.version'], dom: ['[data-barba="wrapper"]'] },
  { name: 'anime.js', cat: 'library', probe: ['anime.version'] },
  { name: 'Handlebars', cat: 'library', probe: ['Handlebars.VERSION'], url: [...cdn('handlebars', 'handlebars.js'), /\/handlebars(?:\.runtime)?(?:\.min)?\.js(?:[?#]|$)/i] },
  { name: 'Mustache.js', cat: 'library', probe: ['Mustache.version'] },
  { name: 'DOMPurify', cat: 'library', probe: ['DOMPurify.version'], url: [...cdn('dompurify'), /\/purify(?:\.min)?\.js(?:[?#]|$)/i] },
  { name: 'Modernizr', cat: 'library', probe: ['Modernizr._version'], url: [/\/modernizr[\w.-]*\.js/i] },
  { name: 'core-js', cat: 'library', probe: ['__core-js_shared__.versions.0.version'] },
  { name: 'Polyfill.io', cat: 'library', url: [d('polyfill.io'), d('polyfill.com'), d('polyfillcache.com')] },
  { name: 'Prototype', cat: 'library', probe: ['Prototype.Version'] },
  { name: 'MooTools', cat: 'library', probe: ['MooTools.version'] },
  { name: 'Dojo', cat: 'library', probe: [['dojo.version', 'dojo.require']] },
  { name: 'YUI', cat: 'library', probe: ['YUI.version'] },
  { name: 'Ext JS', cat: 'library', probe: ['Ext.version', 'Ext.versions.extjs.version'] },
  { name: 'Zepto', cat: 'library', probe: ['Zepto.fn'] },
  { name: 'Hammer.js', cat: 'library', probe: ['Hammer.VERSION'] },
  { name: 'Popper', cat: 'library', probe: ['Popper.createPopper'], url: [/@popperjs\/core@(\d+\.\d+\.\d+)/i, /\/popper(?:\.min)?\.js(?:[?#]|$)/i] },
  { name: 'Tippy.js', cat: 'library', probe: ['tippy.version'] },
  { name: 'SweetAlert2', cat: 'library', probe: ['Swal.version'] },
  { name: 'Select2', cat: 'library', probe: ['jQuery.fn.select2'], dom: ['.select2-container'] },
  { name: 'Flatpickr', cat: 'library', probe: ['flatpickr.l10ns'] },
  { name: 'Fancybox', cat: 'library', probe: ['Fancybox.version', 'jQuery.fancybox.version'], dom: ['[data-fancybox]'] },
  { name: 'Lightbox2', cat: 'library', dom: ['[data-lightbox]'] },
  { name: 'PhotoSwipe', cat: 'library', probe: ['PhotoSwipe'], dom: ['.pswp'] },
  { name: 'Magnific Popup', cat: 'library', probe: ['jQuery.magnificPopup'] },
  { name: 'Isotope', cat: 'library', probe: ['Isotope.Item'] },
  { name: 'Masonry', cat: 'library', probe: ['Masonry.Item'] },
  { name: 'lazysizes', cat: 'library', probe: ['lazySizes.cfg'], dom: ['img.lazyload'] },
  { name: 'Typed.js', cat: 'library', probe: ['Typed'] },
  { name: 'particles.js', cat: 'library', probe: ['particlesJS'] },
  { name: 'tsParticles', cat: 'library', probe: ['tsParticles'] },
  { name: 'Clipboard.js', cat: 'library', probe: ['ClipboardJS'] },
  { name: 'Socket.IO', cat: 'library', probe: ['io.protocol'], url: [/\/socket\.io(?:\.min)?\.js(?:[?#]|$)/i, ...cdn('socket.io-client', 'socket.io')] },
  { name: 'Pusher', cat: 'library', probe: ['Pusher.VERSION'] },
  { name: 'Quill', cat: 'library', probe: ['Quill.imports'] },
  { name: 'TinyMCE', cat: 'library', probe: ['tinymce.majorVersion'] },
  { name: 'CKEditor', cat: 'library', probe: ['CKEDITOR.version', 'CKEDITOR_VERSION'] },
  { name: 'CodeMirror', cat: 'library', probe: ['CodeMirror.version'], dom: ['.CodeMirror', '.cm-editor'] },
  { name: 'Monaco Editor', cat: 'library', probe: ['monaco.editor'], dom: ['.monaco-editor'] },
  { name: 'Prism', cat: 'library', probe: ['Prism.highlightAll'] },
  { name: 'highlight.js', cat: 'library', probe: ['hljs.versionString'], dom: ['code.hljs'] },
  { name: 'MathJax', cat: 'library', probe: ['MathJax.version'], dom: ['mjx-container'] },
  { name: 'KaTeX', cat: 'library', probe: ['katex.version'], dom: ['.katex'] },
  { name: 'Mermaid', cat: 'library', probe: ['mermaid.initialize'] },
  { name: 'Marked', cat: 'library', probe: ['marked.parse'] },
  { name: 'PDF.js', cat: 'library', probe: ['pdfjsLib.version'] },
  { name: 'PixiJS', cat: 'library', probe: ['PIXI.VERSION'] },
  { name: 'Babylon.js', cat: 'library', probe: ['BABYLON.Engine.Version'] },
  { name: 'Phaser', cat: 'library', probe: ['Phaser.VERSION'] },
  { name: 'Apollo Client', cat: 'library', probe: ['__APOLLO_CLIENT__.version', '__APOLLO_STATE__'] },
  { name: 'MobX', cat: 'library', probe: ['__mobxGlobals'] },
  { name: 'SortableJS', cat: 'library', probe: ['Sortable.version'] },
  { name: 'webpack', cat: 'library', special: 'webpack' },
  { name: 'Partytown', cat: 'library', url: [/\/~partytown\//i], dom: ['script[type="text/partytown"]'] },
  { name: 'Cloudflare Rocket Loader', cat: 'library', url: [/\/cdn-cgi\/scripts\/[^/]+\/cloudflare-static\/rocket-loader/i], implies: ['Cloudflare'] },

  // ---------------------------------------------------------------- Analytics
  { name: 'Google Analytics', cat: 'analytics', tracker: 'analytics', ids: 'ga4', url: [d('google-analytics.com'), /googletagmanager\.com\/gtag\/js\?id=G-/i, /\/g\/collect\?/], cookies: ['_ga', /^_ga_/, '_gid'] },
  { name: 'Universal Analytics', cat: 'analytics', tracker: 'analytics', ids: 'ua', probe: ['_gaq.push'], url: [d('google-analytics.com', '(?:analytics|ga)\\.js')], deprecated: 'Universal Analytics stopped processing data on July 1, 2023. The script still loads but collects nothing useful.' },
  { name: 'comScore', cat: 'analytics', tracker: 'analytics', probe: ['COMSCORE'], url: [d('scorecardresearch.com')] },
  { name: 'Hotjar', cat: 'analytics', tracker: 'replay', probe: ['_hjSettings', 'hjSiteSettings'], url: [d('hotjar.com'), d('hotjar.io')], cookies: [/^_hjSession/] },
  { name: 'Microsoft Clarity', cat: 'analytics', tracker: 'replay', url: [d('clarity.ms')], cookies: ['_clck', '_clsk'] },
  { name: 'FullStory', cat: 'analytics', tracker: 'replay', probe: ['_fs_namespace'], url: [d('fullstory.com')] },
  { name: 'Mouseflow', cat: 'analytics', tracker: 'replay', probe: ['mouseflow', '_mfq'], url: [d('mouseflow.com')] },
  { name: 'Smartlook', cat: 'analytics', tracker: 'replay', probe: ['smartlook'], url: [d('smartlook.com'), d('smartlook.cloud')] },
  { name: 'Lucky Orange', cat: 'analytics', tracker: 'replay', url: [d('luckyorange.com'), d('luckyorange.net')] },
  { name: 'Crazy Egg', cat: 'analytics', tracker: 'replay', probe: ['CE2'], url: [d('crazyegg.com')] },
  { name: 'Inspectlet', cat: 'analytics', tracker: 'replay', probe: ['__insp'], url: [d('inspectlet.com')] },
  { name: 'Contentsquare', cat: 'analytics', tracker: 'replay', probe: ['_uxa'], url: [d('contentsquare.net')] },
  { name: 'Mixpanel', cat: 'analytics', tracker: 'analytics', probe: ['mixpanel.__loaded', 'mixpanel.track'], url: [d('mixpanel.com'), d('mxpnl.com')] },
  { name: 'Amplitude', cat: 'analytics', tracker: 'analytics', probe: ['amplitude.getInstance', 'amplitude.track'], url: [d('amplitude.com')] },
  { name: 'Segment', cat: 'analytics', tracker: 'analytics', probe: ['analytics.SNIPPET_VERSION'], url: [d('cdn.segment.com'), d('api.segment.io')] },
  { name: 'Heap', cat: 'analytics', tracker: 'analytics', probe: ['heap.appid'], url: [d('heapanalytics.com'), d('heap-api.com')] },
  { name: 'PostHog', cat: 'analytics', tracker: 'analytics', probe: ['posthog.__loaded', 'posthog.capture'], url: [d('posthog.com')], cookies: [/^ph_.*_posthog$/] },
  { name: 'Matomo', cat: 'analytics', tracker: 'analytics', probe: ['Matomo.getTracker', 'Piwik.getTracker'], url: [/\/(?:matomo|piwik)\.(?:js|php)/i, d('matomo.cloud')], cookies: [/^_pk_id/] },
  { name: 'Yandex Metrica', cat: 'analytics', tracker: 'analytics', probe: ['Ya.Metrika2', 'ym'], url: [d('mc.yandex.ru'), d('mc.yandex.com')] },
  { name: 'Adobe Analytics', cat: 'analytics', tracker: 'analytics', probe: ['s_c_il', 'AppMeasurement'], url: [d('omtrdc.net'), d('2o7.net'), /AppMeasurement/i] },
  { name: 'Plausible', cat: 'analytics', friendly: true, probe: ['plausible'], url: [d('plausible.io')] },
  { name: 'Fathom', cat: 'analytics', friendly: true, url: [d('usefathom.com')] },
  { name: 'Simple Analytics', cat: 'analytics', friendly: true, url: [d('simpleanalyticscdn.com'), d('simpleanalytics.com')] },
  { name: 'Umami', cat: 'analytics', friendly: true, probe: ['umami.track'], url: [d('umami.is')], dom: ['script[data-website-id][src*="umami"]'] },
  { name: 'Cloudflare Web Analytics', cat: 'analytics', friendly: true, url: [d('static.cloudflareinsights.com'), /\/cdn-cgi\/rum/] },
  { name: 'Vercel Analytics', cat: 'analytics', friendly: true, url: [/\/_vercel\/insights\//, d('va.vercel-scripts.com')] },

  // ---------------------------------------------------------------- Tag managers
  { name: 'Google Tag Manager', cat: 'tagmanager', ids: 'gtm', probe: ['google_tag_manager'], url: [d('googletagmanager.com', 'gtm\\.js')], dom: ['iframe[src*="googletagmanager.com/ns.html"]'] },
  { name: 'Google tag (gtag.js)', cat: 'tagmanager', probe: ['gtag'], url: [d('googletagmanager.com', 'gtag/js')] },
  { name: 'Adobe Experience Platform Tags', cat: 'tagmanager', probe: ['_satellite'], url: [d('assets.adobedtm.com')] },
  { name: 'Tealium', cat: 'tagmanager', probe: ['utag'], url: [d('tags.tiqcdn.com')] },

  // ---------------------------------------------------------------- Advertising
  { name: 'Google Ads', cat: 'advertising', tracker: 'advertising', ids: 'aw', url: [d('googleadservices.com'), /googletagmanager\.com\/gtag\/js\?id=AW-/i] },
  { name: 'Google Ad Manager', cat: 'advertising', tracker: 'advertising', probe: ['googletag.pubads'], url: [d('securepubads.g.doubleclick.net')] },
  { name: 'DoubleClick', cat: 'advertising', tracker: 'advertising', url: [d('doubleclick.net'), d('2mdn.net')] },
  { name: 'Google AdSense', cat: 'advertising', tracker: 'advertising', url: [d('pagead2.googlesyndication.com'), d('googlesyndication.com')], dom: ['ins.adsbygoogle'] },
  { name: 'Meta Pixel', cat: 'advertising', tracker: 'social', probe: ['fbq.callMethod', 'fbq.queue', '_fbq'], url: [d('connect.facebook.net', '[^/]+/fbevents\\.js'), /facebook\.com\/tr[/?]/], cookies: ['_fbp'] },
  { name: 'LinkedIn Insight Tag', cat: 'advertising', tracker: 'advertising', probe: ['_linkedin_data_partner_ids', 'lintrk'], url: [d('snap.licdn.com'), d('px.ads.linkedin.com')] },
  { name: 'TikTok Pixel', cat: 'advertising', tracker: 'advertising', probe: ['ttq._i'], url: [d('analytics.tiktok.com')] },
  { name: 'X (Twitter) Pixel', cat: 'advertising', tracker: 'advertising', probe: ['twq'], url: [d('static.ads-twitter.com'), d('analytics.twitter.com')] },
  { name: 'Pinterest Tag', cat: 'advertising', tracker: 'advertising', probe: ['pintrk'], url: [d('s.pinimg.com', 'ct/'), d('ct.pinterest.com')] },
  { name: 'Snap Pixel', cat: 'advertising', tracker: 'advertising', probe: ['snaptr'], url: [d('sc-static.net'), d('tr.snapchat.com')] },
  { name: 'Reddit Pixel', cat: 'advertising', tracker: 'advertising', probe: ['rdt.sendEvent'], url: [d('redditstatic.com', 'ads/'), d('alb.reddit.com')] },
  { name: 'Microsoft Advertising (UET)', cat: 'advertising', tracker: 'advertising', probe: ['UET'], url: [d('bat.bing.com')] },
  { name: 'Criteo', cat: 'advertising', tracker: 'advertising', probe: ['criteo_q'], url: [d('criteo.com'), d('criteo.net')] },
  { name: 'Taboola', cat: 'advertising', tracker: 'advertising', probe: ['_taboola'], url: [d('taboola.com')] },
  { name: 'Outbrain', cat: 'advertising', tracker: 'advertising', probe: ['OBR'], url: [d('outbrain.com')] },
  { name: 'Amazon Ads', cat: 'advertising', tracker: 'advertising', probe: ['apstag'], url: [d('amazon-adsystem.com')] },
  { name: 'AdRoll', cat: 'advertising', tracker: 'advertising', probe: ['__adroll'], url: [d('adroll.com')] },
  { name: 'Prebid.js', cat: 'advertising', tracker: 'advertising', probe: ['pbjs.version'] },
  { name: 'Quantcast', cat: 'advertising', tracker: 'advertising', url: [d('quantserve.com'), d('quantcount.com')] },

  // ---------------------------------------------------------------- Marketing
  { name: 'HubSpot', cat: 'marketing', tracker: 'marketing', probe: ['_hsq', 'hbspt'], url: [d('hs-scripts.com'), d('hs-analytics.net'), d('hsforms.net'), d('hs-banner.com'), d('hscollectedforms.net')], cookies: ['hubspotutk', '__hstc'] },
  { name: 'Klaviyo', cat: 'marketing', tracker: 'marketing', probe: ['_learnq', 'klaviyo'], url: [d('klaviyo.com')] },
  { name: 'Marketo', cat: 'marketing', tracker: 'marketing', probe: ['Munchkin', 'MktoForms2'], url: [d('marketo.net'), d('mktoresp.com')], cookies: ['_mkto_trk'] },
  { name: 'Salesforce Pardot', cat: 'marketing', tracker: 'marketing', probe: ['piAId'], url: [d('pardot.com')] },
  { name: 'Mailchimp', cat: 'marketing', tracker: 'marketing', url: [d('list-manage.com'), d('chimpstatic.com')], dom: ['form[action*="list-manage.com"]'] },
  { name: 'ActiveCampaign', cat: 'marketing', tracker: 'marketing', url: [d('trackcmp.net'), d('activehosted.com')] },
  { name: 'Brevo', cat: 'marketing', tracker: 'marketing', url: [d('sibautomation.com'), d('brevo.com')] },
  { name: 'Customer.io', cat: 'marketing', tracker: 'marketing', probe: ['_cio'], url: [d('customer.io')] },
  { name: 'Braze', cat: 'marketing', tracker: 'marketing', url: [d('braze.com'), d('appboycdn.com')] },
  { name: 'OneSignal', cat: 'marketing', probe: ['OneSignal'], url: [d('onesignal.com')] },

  // ---------------------------------------------------------------- A/B testing
  { name: 'Optimizely', cat: 'abtesting', tracker: 'analytics', probe: ['optimizely'], url: [d('optimizely.com')] },
  { name: 'VWO', cat: 'abtesting', tracker: 'analytics', probe: ['_vwo_code', 'VWO'], url: [d('visualwebsiteoptimizer.com'), d('wingify.com')] },
  { name: 'AB Tasty', cat: 'abtesting', tracker: 'analytics', probe: ['ABTasty'], url: [d('abtasty.com')] },
  { name: 'Kameleoon', cat: 'abtesting', tracker: 'analytics', probe: ['Kameleoon'], url: [d('kameleoon.eu'), d('kameleoon.io')] },
  { name: 'LaunchDarkly', cat: 'abtesting', url: [d('launchdarkly.com')] },
  { name: 'Statsig', cat: 'abtesting', url: [d('statsig.com'), d('statsigapi.net')] },
  { name: 'GrowthBook', cat: 'abtesting', probe: ['_growthbook'], url: [d('growthbook.io')] },
  { name: 'Google Optimize', cat: 'abtesting', url: [d('googleoptimize.com')], deprecated: 'Google Optimize was shut down in September 2023.' },

  // ---------------------------------------------------------------- Consent
  { name: 'OneTrust', cat: 'consent', probe: ['OneTrust', 'OptanonWrapper'], url: [d('cookielaw.org'), d('onetrust.com')], dom: ['#onetrust-banner-sdk', '#onetrust-consent-sdk'], cookies: ['OptanonConsent'] },
  { name: 'Cookiebot', cat: 'consent', probe: ['Cookiebot'], url: [d('cookiebot.com'), d('cookiebot.eu')], cookies: ['CookieConsent'] },
  { name: 'Didomi', cat: 'consent', probe: ['Didomi'], url: [d('privacy-center.org')] },
  { name: 'Osano', cat: 'consent', probe: ['Osano'], url: [d('osano.com')] },
  { name: 'TrustArc', cat: 'consent', probe: ['truste'], url: [d('trustarc.com'), d('truste.com')] },
  { name: 'Usercentrics', cat: 'consent', probe: ['UC_UI', 'usercentrics'], url: [d('usercentrics.eu')] },
  { name: 'CookieYes', cat: 'consent', url: [d('cookieyes.com')], cookies: ['cookieyes-consent'] },
  { name: 'Termly', cat: 'consent', url: [d('termly.io')] },
  { name: 'iubenda', cat: 'consent', probe: ['_iub'], url: [d('iubenda.com')] },
  { name: 'Complianz', cat: 'consent', dom: ['#cmplz-cookiebanner-container', '.cmplz-cookiebanner'], cookies: [/^cmplz_/] },
  { name: 'Quantcast Choice', cat: 'consent', url: [d('cmp.quantcast.com'), d('quantcast.mgr.consensu.org')] },
  { name: 'Sourcepoint', cat: 'consent', url: [d('sourcepoint.mgr.consensu.org'), d('sp-prod.net')] },
  { name: 'Axeptio', cat: 'consent', probe: ['axeptioSettings'], url: [d('axept.io')] },
  { name: 'Klaro', cat: 'consent', probe: ['klaro.show'], url: [/klaro(?:-no-css)?(?:\.min)?\.js/i] },
  { name: 'IAB TCF API', cat: 'consent', probe: ['__tcfapi'] },

  // ---------------------------------------------------------------- Monitoring
  { name: 'Sentry', cat: 'monitoring', probe: ['Sentry.SDK_VERSION', '__SENTRY__'], url: [d('browser.sentry-cdn.com'), d('js.sentry-cdn.com'), d('sentry.io')] },
  { name: 'Datadog RUM', cat: 'monitoring', probe: ['DD_RUM.version', 'DD_LOGS'], url: [d('datadoghq-browser-agent.com'), d('browser-intake-datadoghq.com'), d('browser-intake-datadoghq.eu')] },
  { name: 'New Relic', cat: 'monitoring', probe: ['NREUM'], url: [d('nr-data.net')] },
  { name: 'LogRocket', cat: 'monitoring', tracker: 'replay', probe: ['_lr_loaded', 'LogRocket'], url: [d('lr-ingest.io'), d('lr-in.com'), d('lr-in-prod.com'), d('logr-ingest.com'), d('cdn.logrocket.io')] },
  { name: 'Bugsnag', cat: 'monitoring', probe: ['Bugsnag'], url: [d('bugsnag.com')] },
  { name: 'Rollbar', cat: 'monitoring', probe: ['Rollbar'], url: [d('rollbar.com')] },
  { name: 'Raygun', cat: 'monitoring', probe: ['rg4js'], url: [d('raygun.io')] },
  { name: 'TrackJS', cat: 'monitoring', probe: ['TrackJS'], url: [d('trackjs.com')] },
  { name: 'Dynatrace', cat: 'monitoring', probe: ['dtrum'], cookies: ['dtCookie'] },
  { name: 'AppDynamics', cat: 'monitoring', probe: ['ADRUM'] },
  { name: 'Elastic APM', cat: 'monitoring', probe: ['elasticApm'] },
  { name: 'SpeedCurve', cat: 'monitoring', probe: ['LUX'], url: [d('speedcurve.com')] },
  { name: 'Akamai mPulse', cat: 'monitoring', probe: ['BOOMR.version'], url: [d('go-mpulse.net')] },
  { name: 'Vercel Speed Insights', cat: 'monitoring', url: [/\/_vercel\/speed-insights\//] },

  // ---------------------------------------------------------------- Support
  { name: 'Intercom', cat: 'support', probe: ['Intercom'], url: [d('intercom.io'), d('intercomcdn.com'), d('intercomassets.com')] },
  { name: 'Drift', cat: 'support', probe: ['drift.load'], url: [d('drift.com'), d('driftt.com')] },
  { name: 'Zendesk', cat: 'support', probe: ['zE', 'zESettings'], url: [d('zdassets.com'), d('zendesk.com')] },
  { name: 'Crisp', cat: 'support', probe: ['$crisp'], url: [d('crisp.chat')] },
  { name: 'Tawk.to', cat: 'support', probe: ['Tawk_API'], url: [d('tawk.to')] },
  { name: 'LiveChat', cat: 'support', probe: ['LiveChatWidget', '__lc'], url: [d('livechatinc.com')] },
  { name: 'Tidio', cat: 'support', probe: ['tidioChatApi'], url: [d('tidio.co'), d('tidiochat.com')] },
  { name: 'Freshchat', cat: 'support', probe: ['fcWidget'], url: [d('freshchat.com')] },
  { name: 'Help Scout', cat: 'support', url: [d('beacon-v2.helpscout.net')] },
  { name: 'Olark', cat: 'support', probe: ['olark'], url: [d('olark.com')] },
  { name: 'Chatwoot', cat: 'support', probe: ['$chatwoot', 'chatwootSDK'] },
  { name: 'Gorgias', cat: 'support', url: [d('gorgias.chat'), d('gorgias.io')] },
  { name: 'JivoChat', cat: 'support', probe: ['jivo_api'], url: [d('jivosite.com')] },
  { name: 'Smartsupp', cat: 'support', probe: ['smartsupp'], url: [d('smartsuppchat.com')] },

  // ---------------------------------------------------------------- Payments
  { name: 'Stripe', cat: 'payments', probe: ['Stripe.version'], url: [d('js.stripe.com'), d('m.stripe.network')], dom: ['iframe[src*="js.stripe.com"]'] },
  { name: 'PayPal', cat: 'payments', probe: ['paypal.Buttons', 'PAYPAL.apps'], url: [d('paypal.com', 'sdk/js'), d('paypalobjects.com')] },
  { name: 'Braintree', cat: 'payments', probe: ['braintree.client'], url: [d('braintreegateway.com'), d('braintree-api.com')] },
  { name: 'Square', cat: 'payments', probe: ['Square.payments'], url: [d('squareup.com'), d('squarecdn.com')] },
  { name: 'Adyen', cat: 'payments', probe: ['AdyenCheckout'], url: [d('adyen.com')] },
  { name: 'Klarna', cat: 'payments', probe: ['Klarna'], url: [d('klarna.com'), d('klarnaservices.com'), d('klarnacdn.net')] },
  { name: 'Afterpay', cat: 'payments', probe: ['Afterpay', 'AfterPay'], url: [d('afterpay.com')] },
  { name: 'Affirm', cat: 'payments', probe: ['affirm.ui'], url: [d('affirm.com')] },
  { name: 'Razorpay', cat: 'payments', probe: ['Razorpay'], url: [d('checkout.razorpay.com')] },
  { name: 'Paddle', cat: 'payments', probe: ['Paddle'], url: [d('cdn.paddle.com')] },
  { name: 'Lemon Squeezy', cat: 'payments', probe: ['createLemonSqueezy'], url: [d('lemonsqueezy.com'), d('lmsqueezy.com')] },
  { name: 'Chargebee', cat: 'payments', probe: ['Chargebee'], url: [d('chargebee.com')] },
  { name: 'Recurly', cat: 'payments', probe: ['recurly.configure'], url: [d('recurly.com')] },
  { name: 'Google Pay', cat: 'payments', url: [d('pay.google.com', 'gp/p/js/pay\\.js')] },
  { name: 'Apple Pay', cat: 'payments', url: [d('applepay.cdn-apple.com')], dom: ['apple-pay-button'] },
  { name: 'Mollie', cat: 'payments', probe: ['Mollie'], url: [d('js.mollie.com')] },
  { name: 'Paystack', cat: 'payments', probe: ['PaystackPop'], url: [d('js.paystack.co')] },
  { name: 'Gumroad', cat: 'payments', url: [d('gumroad.com', 'js/')] },

  // ---------------------------------------------------------------- Security & bot protection
  { name: 'reCAPTCHA', cat: 'security', probe: ['grecaptcha'], url: [d('google.com', 'recaptcha/'), d('recaptcha.net'), d('gstatic.com', 'recaptcha/')], dom: ['.g-recaptcha', 'iframe[src*="/recaptcha/"]'] },
  { name: 'hCaptcha', cat: 'security', probe: ['hcaptcha'], url: [d('hcaptcha.com')], dom: ['.h-captcha'] },
  { name: 'Cloudflare Turnstile', cat: 'security', probe: ['turnstile'], url: [d('challenges.cloudflare.com', 'turnstile/')], dom: ['.cf-turnstile'] },
  { name: 'Friendly Captcha', cat: 'security', dom: ['.frc-captcha'], url: [/friendly-challenge/i] },
  { name: 'Arkose Labs', cat: 'security', url: [d('arkoselabs.com'), d('funcaptcha.com')] },
  { name: 'Cloudflare Bot Management', cat: 'security', cookies: ['__cf_bm', 'cf_clearance'] },
  { name: 'Akamai Bot Manager', cat: 'security', cookies: ['_abck', 'bm_sz'] },
  { name: 'HUMAN (PerimeterX)', cat: 'security', cookies: ['_px3', '_pxvid', '_pxhd'], probe: ['_pxAppId'], url: [d('perimeterx.net'), d('px-cdn.net'), d('px-cloud.net')] },
  { name: 'DataDome', cat: 'security', cookies: ['datadome'], url: [d('datadome.co')] },
  { name: 'Imperva', cat: 'security', headers: { 'x-iinfo': /./, 'x-cdn': /Imperva|Incapsula/i }, cookies: [/^incap_ses_/, /^visid_incap_/] },
  { name: 'Sucuri', cat: 'security', headers: { 'x-sucuri-id': /./, 'x-sucuri-cache': /./, server: /^Sucuri/i } },
  { name: 'Cloudflare Email Obfuscation', cat: 'security', url: [/\/cdn-cgi\/scripts\/[^/]+\/cloudflare-static\/email-decode/i], dom: ['a.__cf_email__', '[data-cfemail]'], implies: ['Cloudflare'] },
  { name: 'FingerprintJS', cat: 'security', tracker: 'fingerprinting', probe: ['FingerprintJS'], url: [d('fpjs.io'), d('fpcdn.io'), d('openfpcdn.io'), d('fpnpmcdn.net')] },

  // ---------------------------------------------------------------- Auth & backend services
  { name: 'Firebase', cat: 'auth', probe: ['firebase.SDK_VERSION'], url: [d('gstatic.com', 'firebasejs/(\\d+\\.\\d+\\.\\d+)/'), d('firebaseio.com'), d('firestore.googleapis.com'), d('identitytoolkit.googleapis.com')] },
  { name: 'Supabase', cat: 'auth', url: [d('supabase.co'), ...cdn('@supabase/supabase-js')] },
  { name: 'Auth0', cat: 'auth', probe: ['createAuth0Client'], url: [d('cdn.auth0.com'), /\.auth0\.com\/(?:authorize|oauth|u\/)/i] },
  { name: 'Clerk', cat: 'auth', probe: ['Clerk.version'], url: [/\/npm\/@clerk\/clerk-js@(\d+\.\d+\.\d+)/i, d('clerk.accounts.dev')] },
  { name: 'Okta', cat: 'auth', probe: ['OktaAuth'], url: [d('oktacdn.com')] },
  { name: 'Google Sign-In', cat: 'auth', probe: ['google.accounts.id'], url: [d('accounts.google.com', 'gsi/client')] },
  { name: 'Sign in with Apple', cat: 'auth', probe: ['AppleID.auth'], url: [d('appleid.cdn-apple.com')] },
  { name: 'Algolia', cat: 'auth', probe: ['algoliasearch.version'], url: [d('algolia.net'), d('algolianet.com'), ...cdn('algoliasearch')] },

  // ---------------------------------------------------------------- Video & media
  { name: 'YouTube', cat: 'media', dom: ['iframe[src*="youtube.com/embed"]', 'iframe[src*="youtube-nocookie.com/embed"]', 'lite-youtube'], url: [d('youtube.com', 'iframe_api'), d('youtube.com', 's/player/')] },
  { name: 'Vimeo', cat: 'media', dom: ['iframe[src*="player.vimeo.com"]'], url: [d('player.vimeo.com')] },
  { name: 'Wistia', cat: 'media', probe: ['Wistia'], url: [d('wistia.com'), d('wistia.net')] },
  { name: 'JW Player', cat: 'media', probe: ['jwplayer.version'], url: [d('jwplayer.com'), d('jwpcdn.com')] },
  { name: 'Video.js', cat: 'media', probe: ['videojs.VERSION'], dom: ['.video-js'] },
  { name: 'Plyr', cat: 'media', probe: ['Plyr'], dom: ['.plyr'] },
  { name: 'hls.js', cat: 'media', probe: ['Hls.version'] },
  { name: 'Vidyard', cat: 'media', url: [d('vidyard.com')] },
  { name: 'Loom', cat: 'media', dom: ['iframe[src*="loom.com/embed"]'] },
  { name: 'Spotify Embed', cat: 'media', dom: ['iframe[src*="open.spotify.com/embed"]'] },
  { name: 'SoundCloud', cat: 'media', dom: ['iframe[src*="w.soundcloud.com"]'] },

  // ---------------------------------------------------------------- Widgets & embeds
  { name: 'Google Maps', cat: 'widgets', probe: ['google.maps.version'], url: [d('maps.googleapis.com', 'maps/api/js')], dom: ['iframe[src*="google.com/maps/embed"]'] },
  { name: 'Facebook SDK', cat: 'widgets', tracker: 'social', probe: ['FB.init'], url: [d('connect.facebook.net', '[^/]+/sdk\\.js')] },
  { name: 'X (Twitter) Embed', cat: 'widgets', tracker: 'social', probe: ['twttr.widgets'], url: [d('platform.twitter.com')] },
  { name: 'Instagram Embed', cat: 'widgets', tracker: 'social', probe: ['instgrm'], url: [d('instagram.com', 'embed\\.js')] },
  { name: 'TikTok Embed', cat: 'widgets', url: [d('tiktok.com', 'embed\\.js')] },
  { name: 'Disqus', cat: 'widgets', tracker: 'social', probe: ['DISQUS'], url: [d('disqus.com'), d('disquscdn.com')] },
  { name: 'Giscus', cat: 'widgets', url: [d('giscus.app')] },
  { name: 'Utterances', cat: 'widgets', url: [d('utteranc.es')] },
  { name: 'AddThis', cat: 'widgets', tracker: 'social', probe: ['addthis'], url: [d('addthis.com')], deprecated: 'AddThis was shut down in May 2023; its script no longer works.' },
  { name: 'ShareThis', cat: 'widgets', tracker: 'social', probe: ['__sharethis__'], url: [d('sharethis.com')] },
  { name: 'AddToAny', cat: 'widgets', probe: ['a2a'], url: [d('addtoany.com')] },
  { name: 'Trustpilot', cat: 'widgets', probe: ['Trustpilot'], url: [d('widget.trustpilot.com')] },
  { name: 'Yotpo', cat: 'widgets', url: [d('yotpo.com')] },
  { name: 'Judge.me', cat: 'widgets', url: [d('judge.me')] },
  { name: 'Calendly', cat: 'widgets', probe: ['Calendly'], url: [d('assets.calendly.com')] },
  { name: 'Typeform', cat: 'widgets', probe: ['tf.createWidget'], url: [d('embed.typeform.com')] },
  { name: 'Tally', cat: 'widgets', probe: ['Tally'], url: [d('tally.so')] },
  { name: 'Elfsight', cat: 'widgets', url: [d('elfsight.com'), d('elfsightcdn.com')] },
  { name: 'Gravatar', cat: 'widgets', url: [d('gravatar.com')] },
  { name: 'Google Translate', cat: 'widgets', probe: ['google.translate.TranslateElement'], url: [d('translate.google.com'), d('translate.googleapis.com')] },

  // ---------------------------------------------------------------- WordPress plugins & themes
  { name: 'Elementor', cat: 'wordpress', meta: GEN(/^Elementor ?([\d.]+)?/i), dom: ['.elementor', '[data-elementor-type]'], url: [/\/plugins\/elementor(?:-pro)?\//i], implies: ['WordPress'] },
  { name: 'Divi', cat: 'wordpress', dom: ['#et-boc', '.et_pb_section'], url: [/\/themes\/Divi\//i], implies: ['WordPress'] },
  { name: 'WPBakery', cat: 'wordpress', meta: GEN(/WPBakery/i), dom: ['.vc_row', '.wpb_row'], implies: ['WordPress'] },
  { name: 'Beaver Builder', cat: 'wordpress', dom: ['.fl-builder-content'], implies: ['WordPress'] },
  { name: 'Bricks', cat: 'wordpress', dom: ['[class*="brxe-"]'], implies: ['WordPress'] },
  { name: 'Yoast SEO', cat: 'wordpress', comment: [/Yoast SEO(?: Premium)? plugin v?([\d.]+)?/i], dom: ['script.yoast-schema-graph'], implies: ['WordPress'] },
  { name: 'Rank Math', cat: 'wordpress', comment: [/Rank Math/i], implies: ['WordPress'] },
  { name: 'All in One SEO', cat: 'wordpress', comment: [/All in One SEO(?: Pro)? ?([\d.]+)?/i], meta: GEN(/All in One SEO/i), implies: ['WordPress'] },
  { name: 'Contact Form 7', cat: 'wordpress', dom: ['.wpcf7'], url: [/\/plugins\/contact-form-7\//i], implies: ['WordPress'] },
  { name: 'WPForms', cat: 'wordpress', dom: ['.wpforms-form'], implies: ['WordPress'] },
  { name: 'Gravity Forms', cat: 'wordpress', dom: ['.gform_wrapper'], implies: ['WordPress'] },
  { name: 'Jetpack', cat: 'wordpress', url: [/\/plugins\/jetpack\//i, d('stats.wp.com')], implies: ['WordPress'] },
  { name: 'WP Rocket', cat: 'wordpress', comment: [/WP Rocket/i], implies: ['WordPress'] },
  { name: 'W3 Total Cache', cat: 'wordpress', comment: [/W3 Total Cache/i], implies: ['WordPress'] },
  { name: 'LiteSpeed Cache', cat: 'wordpress', comment: [/LiteSpeed Cache/i], implies: ['WordPress'] },
  { name: 'Autoptimize', cat: 'wordpress', url: [/\/cache\/autoptimize\//i], implies: ['WordPress'] },
  { name: 'Slider Revolution', cat: 'wordpress', dom: ['rs-module', '.rev_slider'], url: [/revslider/i] },
  { name: 'MonsterInsights', cat: 'wordpress', comment: [/MonsterInsights/i], implies: ['WordPress'] },
  { name: 'WPML', cat: 'wordpress', meta: GEN(/^WPML/i), implies: ['WordPress'] },
  { name: 'Site Kit by Google', cat: 'wordpress', meta: GEN(/Site Kit by Google ?([\d.]+)?/i), implies: ['WordPress'] },
  { name: 'Astra', cat: 'wordpress', url: [/\/themes\/astra\//i], implies: ['WordPress'] },
  { name: 'GeneratePress', cat: 'wordpress', url: [/\/themes\/generatepress\//i], implies: ['WordPress'] },
  { name: 'Avada', cat: 'wordpress', url: [/\/themes\/Avada\//i], dom: ['.fusion-builder-row'], implies: ['WordPress'] },
  { name: 'Kadence', cat: 'wordpress', url: [/\/themes\/kadence\//i], implies: ['WordPress'] },
  { name: 'OceanWP', cat: 'wordpress', url: [/\/themes\/oceanwp\//i], implies: ['WordPress'] },
  { name: 'Flatsome', cat: 'wordpress', url: [/\/themes\/flatsome\//i], implies: ['WordPress'] },
  { name: 'Hello Elementor', cat: 'wordpress', url: [/\/themes\/hello-elementor\//i], implies: ['WordPress', 'Elementor'] },

  // ---------------------------------------------------------------- Platform & protocols
  { name: 'HTTP/3', cat: 'platform', special: 'http3' },
  { name: 'HTTP/2', cat: 'platform', special: 'http2' },
  { name: 'Service Worker', cat: 'platform', special: 'serviceWorker' },
  { name: 'Web App Manifest', cat: 'platform', dom: ['link[rel="manifest"]'] },
  { name: 'AMP', cat: 'platform', dom: ['html[amp]', 'html[⚡]'], url: [d('cdn.ampproject.org')] },
  { name: 'HSTS', cat: 'platform', headers: { 'strict-transport-security': /max-age=\d+/i } },
  { name: 'Open Graph', cat: 'platform', dom: ['meta[property^="og:"]'] },
  { name: 'JSON-LD', cat: 'platform', dom: ['script[type="application/ld+json"]'] },
];

export const CATEGORY_LABELS = Object.fromEntries(CATEGORIES);
export const CATEGORY_ORDER = Object.fromEntries(CATEGORIES.map(([k], i) => [k, i]));

/** Hosts known to have served malicious code (polyfill.io supply-chain attack, June 2024). */
export const COMPROMISED_SCRIPT_HOSTS = [
  'polyfill.io', 'polyfill.com', 'polyfillcache.com', 'bootcdn.net', 'bootcss.com',
  'staticfile.net', 'staticfile.org', 'unionadjs.com', 'xhsbpza.com', 'union.macoms.la', 'newcrbpc.com',
];
